### ISSUE TITLE
Add service worker update feature

### ISSUE THREAD

**Issue by bmiddha** [acm-uic/registrum#112]
Add a way to update service workers, and purge cached files.
We can do automatic updates or show the user "Update available" and update the app when they perform an action (button press) or we can also look into other ways of updating it.

Links:
https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#updates
https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#Updating_your_service_worker

**Comment by anarmawala** [comment]
Fixed in #114
