### ISSUE TITLE
Setup production workflow with docker/kubernetes

### ISSUE THREAD

**Issue by alexchomiak** [acm-uic/registrum#23]
🚀 Setup easy deployment with containers.

**Comment by bmiddha** [comment]
Containers are auto published to GitHub Package Registry when a GitHub release is created. We can use webhooks send publish events to Azure App Service.
Azure deployment is a work in progress.

**Comment by bmiddha** [comment]
https://github.com/ckanich-classrooms/final-project-dream-team-1/blob/master/.github/workflows/docker-cd.yml
