### ISSUE TITLE
Cloud Services

### ISSUE THREAD

**Issue by alexchomiak** [acm-uic/registrum#25]
✨ Setup MongoDB Atlas?? ( option in .env file to allow for development environments with local mongodb )

Possibly move container deployment into the cloud?

**Comment by bmiddha** [comment]
We already have a GitHub Actions workflow to publish docker images to GitHub Package Registry when a release is created.

**Comment by bmiddha** [comment]
Default mongo connection uses localhost. It has be configured with `MONGODB_URI` environment variable.
Refer to the `docker-compose.yml` file. It spins up separate containers and a network to connect the containers.
https://github.com/ckanich-classrooms/final-project-dream-team-1/blob/master/.github/workflows/docker-cd.yml
