### ISSUE TITLE
Add Banner API 

### ISSUE THREAD

**Issue by alexchomiak** [acm-uic/registrum#3]
The microservice should interface with the scraper, the scraper should not be built into the microservice itself. This allows for separate scaling of application servers w/ business logic and scrapers.

**Comment by alexchomiak** [comment]
It should also be smart in the notion that the microservice can subscribe and unsubscribe from certain classes from the Banner API. That way it will make minimal requests to the Banner API and retrieve only needed classes.

**Comment by bmiddha** [comment]
To enable subscription and updates from the banner api, we'll have to use webhooks in the api.
When a class has been updated, it can make a call to the webhook, notifying the app about the update.
This webhook will also need to be secured with auth.

**Comment by bmiddha** [comment]
#62
